"""Deterministic seed definitions for users and user stats."""
from datetime import date

DEFAULT_DEV_PASSWORD_HASH = "$2b$12$wlgSkVopJBaFgTtiEH1nH.LB/iyIPhO9lOwVWp6.zcNW1jouO0VEC"  # "password123"

USERS_SEED_DATA = [
    {
        "username": "learner",
        "email": "learner@example.com",
        "password_hash": DEFAULT_DEV_PASSWORD_HASH,
        "avatar_key": "default",
        "is_active": True,
        "onboarding_completed": True,
        "experience_level": "beginner",
        "selected_course_id": 1,
        "stats": {
            "total_xp": 0,
            "current_streak": 0,
            "longest_streak": 0,
            "last_activity_date": None,
            "hearts": 5,
            "max_hearts": 5,
            "gems": 100,
            "daily_goal_xp": 20,
            "daily_goal_progress": 0,
            "daily_goal_date": None,
        },
    },
    {
        "username": "Alex",
        "email": "alex@example.com",
        "password_hash": DEFAULT_DEV_PASSWORD_HASH,
        "avatar_key": "avatar_1",
        "is_active": True,
        "onboarding_completed": True,
        "experience_level": "intermediate",
        "selected_course_id": 1,
        "stats": {
            "total_xp": 850,
            "current_streak": 12,
            "longest_streak": 14,
            "last_activity_date": date(2026, 9, 7),
            "hearts": 5,
            "max_hearts": 5,
            "gems": 450,
            "daily_goal_xp": 20,
            "daily_goal_progress": 20,
            "daily_goal_date": date(2026, 9, 7),
        },
    },
    {
        "username": "Sam",
        "email": "sam@example.com",
        "password_hash": DEFAULT_DEV_PASSWORD_HASH,
        "avatar_key": "avatar_2",
        "is_active": True,
        "onboarding_completed": True,
        "experience_level": "beginner",
        "selected_course_id": 1,
        "stats": {
            "total_xp": 620,
            "current_streak": 8,
            "longest_streak": 10,
            "last_activity_date": date(2026, 9, 7),
            "hearts": 4,
            "max_hearts": 5,
            "gems": 320,
            "daily_goal_xp": 20,
            "daily_goal_progress": 15,
            "daily_goal_date": date(2026, 9, 7),
        },
    },
    {
        "username": "Jordan",
        "email": "jordan@example.com",
        "password_hash": DEFAULT_DEV_PASSWORD_HASH,
        "avatar_key": "avatar_3",
        "is_active": True,
        "onboarding_completed": True,
        "experience_level": "intermediate",
        "selected_course_id": 1,
        "stats": {
            "total_xp": 480,
            "current_streak": 5,
            "longest_streak": 8,
            "last_activity_date": date(2026, 9, 7),
            "hearts": 5,
            "max_hearts": 5,
            "gems": 260,
            "daily_goal_xp": 20,
            "daily_goal_progress": 10,
            "daily_goal_date": date(2026, 9, 7),
        },
    },
    {
        "username": "Taylor",
        "email": "taylor@example.com",
        "password_hash": DEFAULT_DEV_PASSWORD_HASH,
        "avatar_key": "avatar_4",
        "is_active": True,
        "onboarding_completed": True,
        "experience_level": "beginner",
        "selected_course_id": 1,
        "stats": {
            "total_xp": 310,
            "current_streak": 3,
            "longest_streak": 4,
            "last_activity_date": date(2026, 9, 6),
            "hearts": 3,
            "max_hearts": 5,
            "gems": 190,
            "daily_goal_xp": 20,
            "daily_goal_progress": 0,
            "daily_goal_date": date(2026, 9, 6),
        },
    },
    {
        "username": "Casey",
        "email": "casey@example.com",
        "password_hash": DEFAULT_DEV_PASSWORD_HASH,
        "avatar_key": "avatar_5",
        "is_active": True,
        "onboarding_completed": True,
        "experience_level": "beginner",
        "selected_course_id": 1,
        "stats": {
            "total_xp": 170,
            "current_streak": 2,
            "longest_streak": 2,
            "last_activity_date": date(2026, 9, 6),
            "hearts": 5,
            "max_hearts": 5,
            "gems": 140,
            "daily_goal_xp": 20,
            "daily_goal_progress": 0,
            "daily_goal_date": date(2026, 9, 6),
        },
    },
]
